function fh=plot_decode_correct_error(odor4odor,odor4dur,dur4odor,dur4dur,mux4odor,mux4dur)

% plot correct error decoding, maybe encapsulate >>>>>>>>>>>>>>>>>>>>>
mm=[mean(odor4odor.olf.c_result_50su),mean(odor4odor.olf.e_result_50su),...
    mean(odor4dur.dur.c_result_50su),mean(odor4dur.dur.e_result_50su);...
    mean(dur4odor.olf.c_result_50su),mean(dur4odor.olf.e_result_50su),...
    mean(dur4dur.dur.c_result_50su),mean(dur4dur.dur.e_result_50su);...
    mean(mux4odor.olf.c_result_50su),mean(mux4odor.olf.e_result_50su),...
    mean(mux4dur.dur.c_result_50su),mean(mux4dur.dur.e_result_50su);...
    ];

sem=[std(odor4odor.olf.c_result_50su),std(odor4odor.olf.e_result_50su),...
    std(odor4dur.dur.c_result_50su),std(odor4dur.dur.e_result_50su);...
    std(dur4odor.olf.c_result_50su),std(dur4odor.olf.e_result_50su),...
    std(dur4dur.dur.c_result_50su),std(dur4dur.dur.e_result_50su);...
    std(mux4odor.olf.c_result_50su),std(mux4odor.olf.e_result_50su),...
    std(mux4dur.dur.c_result_50su),std(mux4dur.dur.e_result_50su)]...
    ./sqrt(numel(odor4odor.olf.c_result_50su));


fh=figure('Color','w','Position',[100,100,800,240]);
tiledlayout(1,3)
plotOne(mm,sem,1,'olf')
plotOne(mm,sem,2,'dur')
plotOne(mm,sem,3,'mux')
end
function plotOne(mm,sem,idx,ttl)
nexttile(idx)
hold on
bh=bar([mm(idx,1:2);mm(idx,3:4)],'grouped');
errorbar([bh.XEndPoints],[bh.YEndPoints],...
    sem(idx,[1 3 2 4],1,[]),'k.');
ylim([0.4,1]);
set(gca(),'XTick',1:2,...
    'XTickLabel',{'Olf','Dur'},...
    'YTick',0.5:0.25:1,'YTickLabel',50:25:100)
yline(0.5,'k--')
ylabel('Classification accuracy');
title(ttl)
end
