function plot_ln_wt_stp_curve(learn_stats,wt_stats,opt)
arguments
    learn_stats (1,1) struct
    wt_stats (1,1) struct
    opt.levels (1,:) double = 3:5
end
for level=opt.levels
    %diff
    ln_mem=learn_stats.any.postspk(...
    (all(ismember(learn_stats.any.mem_type,1:2),2) | all(ismember(learn_stats.any.mem_type,3:4),2))...
    & learn_stats.any.diff_reg(:,level),:);

    ln_non=learn_stats.any.postspk(...
    all(learn_stats.any.mem_type==0,2)...
    & learn_stats.any.diff_reg(:,level),:);

    wt_mem=wt_stats.any.postspk(...
    (all(ismember(wt_stats.any.mem_type,1:2),2) | all(ismember(wt_stats.any.mem_type,3:4),2))...
    & wt_stats.any.diff_reg(:,level),:);

    wt_non=wt_stats.any.postspk(...
    all(wt_stats.any.mem_type==0,2)...
    & wt_stats.any.diff_reg(:,level),:);

    plotOne(wt_mem,ln_mem,wt_non,ln_non,sprintf('Congruent between regions %d',level))    
    %same    
    ln_mem=learn_stats.any.postspk(...
    (all(ismember(learn_stats.any.mem_type,1:2),2) | all(ismember(learn_stats.any.mem_type,3:4),2))...
    & learn_stats.any.same_reg(:,level),:);
    wt_mem=wt_stats.any.postspk(...
    (all(ismember(wt_stats.any.mem_type,1:2),2) | all(ismember(wt_stats.any.mem_type,3:4),2))...
    & wt_stats.any.same_reg(:,level),:);
    ln_non=learn_stats.any.postspk(...
    all(learn_stats.any.mem_type==0,2)...
    & learn_stats.any.same_reg(:,level),:);
    wt_non=wt_stats.any.postspk(...
    all(wt_stats.any.mem_type==0,2)...
    & wt_stats.any.same_reg(:,level),:);

    plotOne(wt_mem,ln_mem,wt_non,ln_non,sprintf('Congruent within regions %d',level));

end
end

function plotOne(wt_mem,ln_mem,wt_non,ln_non,title_)
    figure('Color','w')
    hold on
    flnm=plot(200:200:2000,fliplr(mean(ln_mem(:,2:end)))*100,'--r');
    fwtm=plot(200:200:2000,fliplr(mean(wt_mem(:,2:end)))*100,'-r');
    flnn=plot(200:200:2000,fliplr(mean(ln_non(:,2:end)))*100,'--k');
    fwtn=plot(200:200:2000,fliplr(mean(wt_non(:,2:end)))*100,'-k');
    legend([flnm,fwtm,flnn,fwtn],...
        {'Congruent-learning ',...
        'Congruent-welltrained',...
        'Non-mem-learning ',...
        'Non-mem-welltrained'});
    title(title_);
    ylabel('Post spike increase (%)')
    ylim([0,5])
    xlim([0,2000])
    set(gca,'XTick',500:500:2000)
    grid on
end