function out=get_wave_ratio(sig_wave,pair_wave)
% 0=NM,1=S1 sust, 2=S1 trans, 3=S2 sust, 4=S2 trans,-1=switched

arguments
    sig_wave (:,2) int8
    pair_wave (:,2) int8
end
out=struct();
for wave_id=1:6
    congr_wave_cnt=nnz(all(pair_wave==wave_id,2));
    if congr_wave_cnt>0
        sig_wave_cnt=nnz(all(sig_wave==wave_id,2));
        [phat,pci]=binofit(sig_wave_cnt,congr_wave_cnt);
        out.congr_wave(wave_id,:)=[wave_id,phat,pci,sig_wave_cnt,congr_wave_cnt];
    else
        out.congr_wave(wave_id,:)=[wave_id,0,0,0,0,0];
    end
end

congr_inter_wave_cnt=nnz((pair_wave(:,1)==1 & pair_wave(:,2)==3)...
    | (pair_wave(:,1)==3 & pair_wave(:,2)==1)...
    | (pair_wave(:,1)==2 & pair_wave(:,2)==4)...
    | (pair_wave(:,1)==4 & pair_wave(:,2)==2));
if congr_inter_wave_cnt>0
    sig_inter_wave_cnt=nnz((sig_wave(:,1)==1 & sig_wave(:,2)==3)...
        | (sig_wave(:,1)==3 & sig_wave(:,2)==1)...
        | (sig_wave(:,1)==2 & sig_wave(:,2)==4)...
        | (sig_wave(:,1)==4 & sig_wave(:,2)==2));
    [phat,pci]=binofit(sig_inter_wave_cnt,congr_inter_wave_cnt);
    out.congr_inter_wave=[phat,pci,sig_inter_wave_cnt,congr_inter_wave_cnt];
else
    out.congr_inter_wave=[0,0,0,0,0];
end

congr_overlapped_wave_cnt=nnz((pair_wave(:,1)==1 & pair_wave(:,2)==5)...
    | (pair_wave(:,1)==5 & pair_wave(:,2)==1)...
    | (pair_wave(:,1)==2 & pair_wave(:,2)==6)...
    | (pair_wave(:,1)==6 & pair_wave(:,2)==2)...
    | (pair_wave(:,1)==3 & pair_wave(:,2)==5)...
    | (pair_wave(:,1)==5 & pair_wave(:,2)==3)...
    | (pair_wave(:,1)==4 & pair_wave(:,2)==6)...
    | (pair_wave(:,1)==6 & pair_wave(:,2)==4)...
    );
if congr_overlapped_wave_cnt>0
    sig_overlapped_wave_cnt=nnz((sig_wave(:,1)==1 & sig_wave(:,2)==5)...
        | (sig_wave(:,1)==5 & sig_wave(:,2)==1)...
        | (sig_wave(:,1)==2 & sig_wave(:,2)==6)...
        | (sig_wave(:,1)==6 & sig_wave(:,2)==2)...
        | (sig_wave(:,1)==3 & sig_wave(:,2)==5)...
        | (sig_wave(:,1)==5 & sig_wave(:,2)==3)...
        | (sig_wave(:,1)==4 & sig_wave(:,2)==6)...
        | (sig_wave(:,1)==6 & sig_wave(:,2)==4));
    [phat,pci]=binofit(sig_overlapped_wave_cnt,congr_overlapped_wave_cnt);
    out.congr_overlapped_wave=[phat,pci,sig_overlapped_wave_cnt,congr_overlapped_wave_cnt];
else
    out.congr_overlapped_wave=[0,0,0,0,0];
end
end

