if ispc
    homedir='k:\neupix\wyt';
    addpath('K:\Lib\buzcode\buzcode\io')
    addpath('K:\Lib\buzcode\buzcode\utilities\')
    addpath('K:\Lib\buzcode\buzcode\analysis\spikes\correlation\')
    addpath('K:\Lib\buzcode\buzcode\analysis\spikes\functionalConnectionIdentification\')
    addpath('K:\Lib\buzcode\buzcode\visualization\')
    addpath('K:\Lib\buzcode\buzcode\externalPackages\FMAToolbox\General\');
    addpath('K:\Lib\buzcode\buzcode\externalPackages\FMAToolbox\Helpers\');
    addpath(fullfile('K:','Lib','npy-matlab-master','npy-matlab'))
    addpath(fullfile('K:','Lib','fieldtrip-20200320'))
    ft_defaults
else
    homedir='/home/zx/neupix/wyt';
    addpath('~/Lib/buzcode/buzcode/io')
    addpath('~/Lib/buzcode/buzcode/utilities/')
    addpath('~/Lib/buzcode/buzcode/analysis/spikes/correlation/')
    addpath('~/Lib/buzcode/buzcode/analysis/spikes/functionalConnectionIdentification/')
    addpath('~/Lib/buzcode/buzcode/visualization/')
    addpath('~/Lib/buzcode/buzcode/externalPackages/FMAToolbox/General/');
    addpath('~/Lib/buzcode/buzcode/externalPackages/FMAToolbox/Helpers/');
    addpath(fullfile('npy-matlab-master','npy-matlab'))
    addpath('fieldtrip-20200320')
    ft_defaults
end