rule all:
	input:
		"binary/chain_loop_in_nests.fig",
		"binary/chains_consist_incon.fig",
		"binary/corr_err_trans_sust_AUC_olf.fig",
		"binary/delay_iti_alt_path_per_spk.fig",
		"binary/delay_iti_motif_spike_per_sec.fig",
		"binary/delay_vs_iti_per_sec.fig",
		"binary/FC_congru_incon_nonmem.fig",
		"binary/nested_loop_time_constant.fig",
		"binary/nests_graph_stats.fig",
		"binary/nests_per_region_degree.fig",
		"binary/sschain_time_constant.fig",
		"binary/ssloop_time_constant.fig",
		"binary/su_decoding.fig",
		"binary/su_trans_sustain.fig"


rule trials_dict:
	input:
	output:
		"binary/trials_dict.mat"
	shell:
		'matlab -noFigureWindows -batch "behav.get_trials_dict()"'

rule delay_vs_iti_covered_per_sec:
	input:
		"binary/delay_iti_runlength_covered.mat",
		"binary/trials_dict.mat"
	output:
		"binary/delay_vs_iti_per_sec.fig",
		"binary/motif_cover_per_sec.mat"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.delay_vs_iti_per_sec()"'

rule delay_vs_iti_runlength_covered:
	input:
		"binary/motif_replay.mat"
	output:
		"binary/delay_iti_runlength_covered.mat"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.delay_vs_iti()"'

rule rings_tag_trl:
	input:
		"binary/sums_ring_stats_all.mat",
		"binary/su_meta.mat",
		"binary/wrs_mux_meta.mat"
	output:
		"binary/rings_tag_trl.mat"
	shell:
		'matlab -noFigureWindows -batch "bz.rings.rings_time_constant.stats(load_file=false,skip_save=false,compress=true)"'
		
rule wrs_mux_meta:
	output:
		"binary/wrs_mux_meta.mat"
	shell:
		'matlab -noFigureWindows -batch "ephys.get_wrs_mux_meta(save_file=true,load_file=false)"'
		
rule su_meta:
	output:
		"binary/su_meta.mat"
	shell:
		'matlab -noFigureWindows -batch "ephys.util.load_meta(save_file=true,adjust_white_matter=true)"'

rule replay_stats:
	input:
		"binary/trials_dict.mat",
		"binary/chain_tag_all_trl.mat",
		"binary/rings_tag_trl.mat"
	output:
		"binary/motif_replay.mat"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.stats_tbl(skip_save=false)"'

rule delay_iti_motif_per_spike:
	input:
		"binary/motif_replay.mat"
	output:
		"binary/delay_vs_iti_pivot_spike.mat"	
	shell:
		'matlab -noFigureWindows -batch "wave.replay.delay_vs_iti_motif_per_spike(skip_save=false)"'

rule delay_iti_motif_spike_plot:
	input:
		"binary/delay_vs_iti_pivot_spike.mat"	
	output:
		"binary/delay_iti_alt_path_per_spk.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.plot_pivot()"'
		
rule motif_nest:
	input:
		"binary/chain_tag_all_trl.mat",
		"binary/rings_tag_trl.mat",
		"binary/trials_dict.mat"
	output:
		"binary/nested_loops_stats.mat",
		"binary/SingleSpikeChainedLoopCid.mat",
		"binary/nests_graph_stats.fig",
		"binary/nests_per_region_degree.fig",
		"binary/chain_loop_in_nests.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.module_motif_asso_composite(skip_save=false)"'

rule nest_loop_runlength:
	input:
		"binary/delay_iti_runlength_covered.mat"
	output:
		"binary/nested_loop_time_constant.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.loop.nested_loop_time_const()"'

rule delay_vs_iti_spike_per_sec:
	input:
		"binary/motif_replay.mat",
		"binary/trials_dict.mat"
	output:
		"binary/delay_iti_motif_spike_per_sec.mat",
		"binary/delay_iti_motif_spike_per_sec.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.delay_vs_iti_motif_spike_per_sec(skip_save=false)"'

rule sschain_time_constant:
	input:
		"binary/motif_replay.mat"
	output:
		"binary/sschain_time_constant.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.chain.sschain_time_const(skip_save=false)"'
		
rule ssloop_time_constant:
	input:
		"binary/motif_replay.mat"
	output:
		"binary/ssloop_time_constant.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.loop.ssloop_time_const(skip_save=false)"'
		
rule su_decoding:
	input:
		"binary/su_meta.mat",
		"binary/wrs_mux_meta.mat"
	output:
		"binary/su_decoding.mat",
		"binary/su_decoding.fig"
	shell:
		'matlab -noFigureWindows -batch "ephys.su_decoding_corr_err(skip_save=false)"'

rule su_trans_sustain_percentage:
	input:
		"binary/wrs_mux_meta.mat"
	output:
		"binary/su_trans_sustain.fig"
	shell:
		'matlab -noFigureWindows -batch "ephys.sust_trans_bar_w_mix(skip_save=false)"'
		
rule FC_congru_incon_nonmem:
	input:
		"binary/wrs_mux_meta.mat"
	output:
		"binary/FC_congru_incon_nonmem.fig"
	shell:
		'matlab -noFigureWindows -batch "bz.inter_wave_pct(odor_only=true,skip_save=false)"'

rule sust_trans_correct_err_AUC:
	input:
		"binary/wrs_mux_meta.mat"
	output:
		"binary/corr_err_trans_sust_AUC_olf.fig",
		"binary/corr_err_trans_sust_AUC.mat"
	shell:
		'matlab -noFigureWindows -batch "ephys.sust_trans_correct_error(odor_only=true,skip_save=false)"'
		
rule gen_shuffled_coupling:
	output:
		"binary/bz_ring_shufs.mat"
	threads: 32
	shell:
		'matlab -noFigureWindows -batch "bz.shuffle_conn_bz_alt(poolsize={threads},rpt=100)"'

rule chain_consist_incon:
	input:
		"binary/su_meta.mat",
		"binary/wrs_mux_meta.mat"
	output:
		"binary/chains_consist_incon.fig"
		"binary/chains_consist_incon_nonmem.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.chain.chains_consist_incon(skip_save=false,shuf=true)"'
		'matlab -noFigureWindows -batch "wave.chain.chains_consist_incon(skip_save=false,shuf=true,non_mem=true)"'

rule gen_chain_tag_file:
	input:
		"binary/su_meta.mat",
		"binary/wrs_mux_meta.mat"
	output:
		"binary/chain_tag_all_trl.mat"
	threads: 52
	shell:
		'matlab -noFigureWindows -batch "wave.chain.gen_chain_tag_file(poolsize={threads})"'
