rule trials_dict:
	input:
	output:
		"binary/trials_dict.mat"
	shell:
		'matlab -noFigureWindows -batch "behav.get_trials_dict()"'

rule delay_vs_iti_covered_per_sec:
	input:
		"binary/delay_iti_runlength_covered.mat",
		"binary/trials_dict.mat"
	output:
		"binary/delay_vs_iti_per_sec.fig",
		"binary/motif_cover_per_sec.mat"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.delay_vs_iti_per_sec()"'

rule delay_vs_iti_runlength_covered:
	input:
		"binary/motif_replay.mat"
	output:
		"binary/delay_iti_runlength_covered.mat"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.delay_vs_iti()"'

rule rings_tag_trl:
	input:
		"binary/sums_ring_stats_all.mat",
		"binary/su_meta.mat",
		"binary/wrs_mux_meta.mat"
	output:
		"binary/rings_tag_trl.mat"
	shell:
		'matlab -noFigureWindows -batch "bz.rings.rings_time_constant.stats(load_file=false,skip_save=false,compress=true)"'
		
rule wrs_mux_meta:
	output:
		"binary/wrs_mux_meta.mat"
	shell:
		'matlab -noFigureWindows -batch "ephys.get_wrs_mux_meta(save_file=true,load_file=false)"'
		
rule su_meta:
	output:
		"binary/su_meta.mat"
	shell:
		'matlab -noFigureWindows -batch "ephys.util.load_meta(save_file=true,adjust_white_matter=true)"'

rule replay_stats:
	input:
		"binary/trials_dict.mat",
		"binary/chain_tag_all_trl.mat",
		"binary/rings_tag_trl.mat"
	output:
		"binary/motif_replay.mat"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.stats_tbl(skip_save=false)"'

rule delay_iti_motif_per_spike:
	input:
		"binary/motif_replay.mat"
	output:
		"binary/delay_vs_iti_pivot_spike.mat"	
	shell:
		'matlab -noFigureWindows -batch "wave.replay.delay_vs_iti_motif_per_spike(skip_save=false)"'

rule delay_iti_motif_spike_plot:
	input:
		"binary/delay_vs_iti_pivot_spike.mat"	
	output:
		"binary/delay_iti_alt_path_per_spk.fig"
	shell:
		'matlab -noFigureWindows -batch "wave.replay.plot_pivot()"'
		
